In [1]:
import pandas as pd 

df=pd.read_csv("Table.csv")
print(df)

   year  persons  males  females
0  1951    18.33  27.16     8.55
1  1961    28.30  40.40    15.35
2  1971    35.45  45.96    21.57
3  1981    43.57  56.38    29.76
4  1991    52.24  64.13    39.23


In [13]:
import pandas as pd 

df=pd.read_csv("Table.csv")
print(df)

data=df[['persons','males','females']]
print(data)

print(data.mean(axis=0))
print(data.std(axis=0))

# mean_removed_data = preprocessing.scale(data)
# print(mean_removed_data.mean(axis=0))
# print(mean_removed_data.std(axis=0))


data=df[['persons','males','females']]
scaller_model=preprocessing.MinMaxScaler()

op=scaller_model.fit_transform(data)
print(op)

   year  persons  males  females
0  1951    18.33  27.16     8.55
1  1961    28.30  40.40    15.35
2  1971    35.45  45.96    21.57
3  1981    43.57  56.38    29.76
4  1991    52.24  64.13    39.23
   persons  males  females
0    18.33  27.16     8.55
1    28.30  40.40    15.35
2    35.45  45.96    21.57
3    43.57  56.38    29.76
4    52.24  64.13    39.23
persons    35.578
males      46.806
females    22.892
dtype: float64
persons    13.152694
males      14.313458
females    12.025204
dtype: float64
[[0.         0.         0.        ]
 [0.29401357 0.35812821 0.22164276]
 [0.50486582 0.50852042 0.4243807 ]
 [0.74432321 0.79037057 0.69132986]
 [1.         1.         1.        ]]


In [3]:
import numpy as np 

from sklearn import preprocessing

data=np.array([[3,5],[7,4],[2,4]])

scaller_model=preprocessing.MinMaxScaler()

op=scaller_model.fit_transform(data)
print(op)

[[0.2 1. ]
 [1.  0. ]
 [0.  0. ]]


In [4]:
import numpy as np 

from sklearn import preprocessing

data=np.array([[3,5],[7,4],[2,4]])

scaller_model=preprocessing.MinMaxScaler()

op=scaller_model.fit_transform(data)
print(op)


[[0.2 1. ]
 [1.  0. ]
 [0.  0. ]]


# Normlization

In [10]:
data=np.array([[3,5],[7,4],[2,4]])

op=preprocessing.normalize(data,norm='l1')
print(op)

[[0.375      0.625     ]
 [0.63636364 0.36363636]
 [0.33333333 0.66666667]]


# Binarization

In [12]:
import numpy as np 

from sklearn import preprocessing

data=np.array([[3,5],[7,4],[2,4]])
binarized_data=preprocessing.Binarizer(threshold=5)
op=binarized_data.fit_transform(data)
print(data)
print(op)


[[3 5]
 [7 4]
 [2 4]]
[[0 0]
 [1 0]
 [0 0]]


# Label Encoding

In [17]:
from sklearn.preprocessing import LabelEncoder

data=['apple','banana','mango','grapes','apple','banana','mango','grapes']
labeled_data=preprocessing.LabelEncoder()
op=labeled_data.fit_transform(data)
print(data)
print(op)

#testing the model
test_data=['banana','grapes']
test_op=labeled_data.transform(test_data)
print(test_op)

#inverse testing
test_data=[3,0]
op=labeled_data.inverse_transform(test_data)
print(op)

['apple', 'banana', 'mango', 'grapes', 'apple', 'banana', 'mango', 'grapes']
[0 1 3 2 0 1 3 2]
[1 2]
['mango' 'apple']
